### ISSUE TITLE
Compilation/runtime error of MainRobotGen.m

### ISSUE THREAD

**Issue by serena-ivaldi** [serena-ivaldi/learnOptimWBC#1]
Hi,
I have a fresh installation with Ubuntu 14.04 and Matlab 2013a, using gcc-4.4.
I get runtime errors when running MainRobotGen.m with both flags (kinematics only or everything)

06-Jun-2016 16:19:53    Generating jacobian m-function with respect to the robot end-effector frame  done!
Error using CodeGenerator/genccodejacobian (line 46)
Save symbolic expressions to disk first!

Error in CodeGenerator/genjacobian (line 89)
    CGen.genccodejacobian;

Error in CodeGenerator/geneverything (line 302)
            [J0,Jn] = CGen.genjacobian(rpy,eul,jacob0);

Error in MainRobotGen (line 19)
   cGen.geneverything('norpy','noeul',false);

**Comment by serena-ivaldi** [comment]
Found one first bug in the missing copy of genccodejacobian.m from the ChangedFile to the rcvtools.
I added it in the startup file.

**Comment by serena-ivaldi** [comment]
New bug:
Deriving gravitational load vectorError using frne
frne: Q must have Naxis columns

Error in SerialLink/rne (line 81)
        [varargout{1:nargout}] = frne(robot, varargin{:});

Error in SerialLink/gravload (line 43)
        tg = rne(robot, q, zeros(size(q)), zeros(size(q)));

Error in CodeGenerator/gengravload (line 56)
G = tmpRob.gravload(q);

Error in CodeGenerator/geneverything (line 304)
            [G] = CGen.gengravload;

Error in MainRobotGen (line 19)
   cGen.geneverything('norpy','noeul',false);

**Comment by VModugno** [comment]
fixed by changing the package installation procedure
